name = "atlas"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "atlas-db"
database_id = "atlas-db-dev"
