name = "atlas"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "atlas-db"
database_id = "ff7346b0-3421-4381-b73a-4886b6c23836"

[env.preview.vars]
ATLAS_ADMIN_USER_IDS = "6dZFB461PBduB32YyDsv8mJgsMuprFkm"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "atlas-db"
database_id = "ff7346b0-3421-4381-b73a-4886b6c23836"
